server {
    listen 80;
    server_name ulplay.com www.ulplay.com;

    # ACME challenge (Let's Encrypt)
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    # Redirect everything else to HTTPS
    location / {
        limit_req zone=ulplay_dynamic burst=8;
        return 301 https://$host$request_uri;
    }
}
